# Generated by Django 5.2.2 on 2025-06-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_add_savings_categories"),
        ("tracker", "0004_alter_category_name_alter_category_unique_together"),
    ]

    operations = []
